### ISSUE TITLE
Faster way to add dependencies

### ISSUE THREAD

**Issue by gpeal** [jmfayard/refreshVersions#123]
**Describe the solution you'd like**
If I understand this plugin correctly, to add a new dependency:
* Add an implementation/api dependency to a module's build.gradle file
* Run `./gradlew buildSrcVersions`
* The script will recompile the Versions and Libs file.

However, the gradle task takes over 5 minutes on our project. This makes it a real pain to add new dependencies.

Is there a faster way of doing this or could this be improved?

**Comment by jmfayard** [comment]
Gabriel, you are correct. @gpeal

This why we are building a better solution to do this in two parts:

1. We will replace `buildSrc/.../Libs.kt` by a new Gradle plugin:
2. We will replace `buildSrc/.../Versions.kt` by `./gradlew refreshVersions` that produces a file `versions.properties`

On 1), if you think about  it the `buildSrc` is a private Gradle plugin. But in the Android world for example, 80% of the dependencies we are using are the same: androidx, square, jakewharton, unittesting, ... So the new plugin will contain them all, avoiding the need to recompile `Libs.kt` for all the common dependencies. 

See here https://github.com/LouisCAD/Splitties/tree/develop/plugin/src/main/kotlin/com/louiscad/splitties

On 2), instead of having `./gradlew buildSrcVersions` generate `buildSrc/.../Versions.kt`, I am polishing a simplified plugin that contains the task `./gradlew refreshVesions`  that generates a file `versions.properties`

This is the same thing but more performant because it avoids recompiling the `buildSrc`, which basically means you are doing a clean build every time, which fucks up with compilation avoidance.

See  [Long term plan: focus on refreshVersions #104](https://github.com/jmfayard/buildSrcVersions/issues/104)

**Comment by gpeal** [comment]
@jmfayard Definitely looking forward to that :) Any eta?

**Comment by jmfayard** [comment]
@gpeal I would say 2-4 weeks, but that's not a promise :)

**Comment by jmfayard** [comment]
Done in refreshVersion!

https://jmfayard.github.io/refreshVersions/adding-dependencies/

**Comment by gpeal** [comment]
https://jmfayard.github.io/refreshVersions/add-dependencies/ is the correct link for anybody looking for the above link.

**Comment by LouisCAD** [comment]
Yep, fixed the comment above for future reference 😉
The new doc should be alright now, but please let us know if anything is unclear or off, and feel free to file but reports, ideas or feature requests.

**Comment by gpeal** [comment]
@LouisCAD Thanks! We'll be upgrading in the next week or so at Tonal :)

**Comment by LouisCAD** [comment]
Note that migration is currently a little time consuming as you have to review each dependency that is not using the version placeholder. We documented the experimental status and the planned improvements here: https://jmfayard.github.io/refreshVersions/migration/ (Planned to be done before Christmas, roughly).

Now, finding the updates is way faster than before (takes about 10 seconds on fairly large projects), so it might be worth "paying" that migration cost if you often wait for it to find updates.

You can see our priorities here: https://github.com/jmfayard/refreshVersions/projects/4

**Comment by gpeal** [comment]
@LouisCAD Yeah, we decided to pay it down now and appreciate the continued work you are putting into this project. We ran into #265 and #279 btw.
