### ISSUE TITLE
Use of BOM style of dependency version injection

### ISSUE THREAD

**Issue by simonsickle** [jmfayard/refreshVersions#270]
**Is your feature request related to a problem? Please describe.**

When using refreshVersions, we must use a placeholder `_` for it to work. This can create a wall of warnings in Android Studio.

 
**Describe the solution you'd like**

Recently, Firebase published a BOM which allowed all of their libraries to be used without any version or placeholder.

```
implementation(platform("com.google.firebase:firebase-bom:25.12.0"))
implementation("com.google.firebase:firebase-analytics-ktx")
```

It would be very nice to be able to use this same mechanism to fill out versions for other libraries, if possible, to avoid the massive wall of yellow warnings when I enter my build scripts.

 
**Describe alternatives you've considered**

- Keep using the underscore
- Attempt to make a BOM for my own library set (headache)

**Additional context**

**Comment by LouisCAD** [comment]
Hi @simonsickle!
We cannot ditch the version placeholder for no version specified at all because it'd be ambiguous with BoM.

Now, I encountered the same issue as you, and I found a great way to get rid of it, that we'll document and probably provide by default in the future for people to commit into their project:

Create a `lint.xml` file at the root of your Android gradle project if it doesn't exist yet, and ignore the two warnings you're facing:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<lint>
    <!-- Irrelevant checks that would trigger on usage of the version placeholder for refreshVersions -->
    <issue id="GradleDependency" severity="ignore" />
    <issue id="GradlePluginVersion" severity="ignore" />
</lint>
```
