### ISSUE TITLE
Have a staging website

### ISSUE THREAD

**Issue by LouisCAD** [jmfayard/refreshVersions#276]
To review website updates more comfortably (i.e. not developing directly in production), we need to be able to deploy to another domain.

GitHub pages don't seem to make this easy, so I'm considering using Firebase Hosting for that (its free plan will be more than enough for PR reviews).

I found this which should easily be usable in GitHub Actions (despite it showing an example for Gitlab): https://github.com/tkikuchi2000/mkdocs-firebase-pipeline

**Comment by jmfayard** [comment]
I gave it some thoughts.

I think your real issue can be solved in the future by:

1. not pushing directly to `master`/`mkdocs` 
2. running `$ mkdocs serve` locally when reviewing a pull request 

When the website was in its infancy, it made sense to push directly to production, because higher velocity and no-one was using it anyway.

Once we it has replaced the current docs and people use it, running mkdocs serve locally is a superior solution. A staging website would be read by no-one except the pull request reviewer. By running the website locally you get that too. But much important you can update the docs that need to be updated and see in love whether that looks good.

**Comment by LouisCAD** [comment]
I think both options are interesting. The ability to not have to check out a PR to see edits is nice to me, and more convenient to also preview on mobile.

**Comment by LouisCAD** [comment]
I added a "workflow" in #280 so it now uploads the built website as artifacts that can be downloaded as a zip file.
Then, using the website locally doesn't require to install mkdocs and python stuff on your machine, all I have to do is:
1. Unzip the downloaded artifact
2. Drag and drop the unzipped directory to IntelliJ IDEA
3. Open the `index.html` file in the IDE
4. Click on the icon of my favorite browser to launch the IntelliJ IDEA basic web server and have it resolve the index.html pages.

**Comment by LouisCAD** [comment]
Regarding Firebase Hosting, I've been exploring it a little more and here's what I found that is interesting for us:
1. Even though Firebase as a Google product is not really available in China (unlike GitHub), websites using Firebase Hosting and a custom domain are reachable through the firewall
2. We can get server-side and CDN-side analytics with Firebase Hosting
3. There's [some docs about deploying via GitHub Actions](https://firebase.google.com/docs/hosting/github-integration) for preview and/or live channels, and [a GitHub Action](https://github.com/marketplace/actions/deploy-to-firebase-hosting) that we can leverage.
4. Firebase Hosting has a free tier allowing custom domains that should be enough for us (I guess you knew).

**Comment by jmfayard** [comment]
We can use ngrok for that
