### ISSUE TITLE
Ability to ignore alpha/beta versions

### ISSUE THREAD

**Issue by tasomaniac** [jmfayard/refreshVersions#311]
**Is your feature request related to a problem? Please describe.**

The update comments on versions.properties are really helpful. But in case we never use alpha versions in a project, alpha version updates are not really useful.
 
**Describe the solution you'd like**

Provide a mechanism to disable checking for alpha builds. 

Versions plugin has similar functionality: https://github.com/ben-manes/gradle-versions-plugin#revisions

**Comment by jmfayard** [comment]
I have implemented this feature in https://github.com/jmfayard/refreshVersions/pull/347

But one of us is not sure yet if it's right and we don't want to ship a bad API
That's why your feedback would be really appreciated
@bjonnh @moritzruth @msiemens @simonbasle @brewin @Sh4dowSoul 

This is how it would work to ignore all non-stable releases

```
refreshVersions {
    rejectVersionIf {
        candidate.stabilityLevel != StabilityLevel.Stable
    }
}
```

Same but for retrofit you want all versions

```
refreshVersions {
    rejectVersionIf {
        moduleId.group != "com.square.retrofit" && candidate.stabilityLevel != StabilityLevel.Stable
    }
}
```

Same but you want to see all updates for the key `version.coroutines`

```
refreshVersions {
    rejectVersionIf {
        versionKey != "version.kotlinx.coroutines" && candidate.stabilityLevel != StabilityLevel.Stable
    }
}
```


Or maybe you want to see alpha versions if you are already using an alpha version, otherwise you want to see only stable versions

```
refreshVersions {
    rejectVersionIf {
        candidate.stabilityLevel.isLessStableThan(current.stabilityLevel)
    }
}
```

Questions:

Does that feel right?

Does that solve your use cases? 

If not, what are they?

**Comment by simonbasle** [comment]
that filter api seems good to me. caveat: I have only _evaluated _the plugin so far, not yet made the jump. but yeah, it was definitely annoying to see unstable version comments and this looks like a good improvement.

**Comment by jmfayard** [comment]
FWI we have two sister projects with refreshVersions already setup if you want to evaluate it

https://github.com/jmfayard/kotlin-cli-starter
https://github.com/LouisCAD/kotlin-libraries-playground

this is what `refreshVersionsIf` in action looks liks
https://github.com/LouisCAD/kotlin-libraries-playground/commit/e3838f16bb0cda35caadad030b8198742ff12bfb

**Comment by jmfayard** [comment]
Interesting feedback from Ben Manes here

https://github.com/ben-manes/gradle-versions-plugin/issues/519#issuecomment-845689749

**Comment by LouisCAD** [comment]
Indeed, I think this research and insights will help a lot in designing the feature in refreshVersions.

**Comment by LouisCAD** [comment]
Hello, version 0.20.0 is out and brings the `rejectVersionIf { … }` predicate, with an API that makes it easy to filter by stability level if you need that.
