### ISSUE TITLE
Missing plugin version should add `plugin.the.plugin=[current version] in the versions.properties file

### ISSUE THREAD

**Issue by dave08** [jmfayard/refreshVersions#334]
Currently this needs to be manually added with the current version before taking out the version from the plugins block.

**Comment by LouisCAD** [comment]
Hello, unfortunately, there's no way for refreshVersions to help here, other than doing a complex operation involving running the build twice in a row, which we won't do because of the time it can get the developers to lose.

**Comment by dave08** [comment]
Can it be done when running the `refreshVersions` gradle task @LouisCAD ? That's the first thing I did that I thought would help when removing the plugin's versions...

**Comment by LouisCAD** [comment]
It cannot either. The complex operation I was referring to would involve seeing if the build fails because of undefined version.

**Comment by dave08** [comment]
Oh, thanks for the explanation! I guess manual is the way to go then. Another thing though, maybe have a `Plugins` object to provide those versions and write to the file just like the ones in the dependencies block? Then we wouldn't leave it out anymore.

**Comment by LouisCAD** [comment]
The Gradle plugin ids are short enough that I don't think it's necessary to do that, plus we wouldn't be able to use the version placeholder here, because the Gradle APIs don't allow that.
Maybe Gradle could introduce something allowing it in the future, but it's not a priority for refreshVersions, and probably even less for Gradle.

That said, I might add a specific Gradel task to add the latest most stable version of a given gradle plugin id at some point, but given it's not that hard right now, it's not high in the priority list for now, I prefer to be honest with you.
