### ISSUE TITLE
Continuous Deployment

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#340]
We want to move from big risky stressful releases to smaller less risky less stressfull releases.

We should use feature flags and other techniques that make new releases less risky.

In a spirit of continuous deployment, every commit should be published somewhere.

In the past we used to have "dev release" published on bintray, but bintray is dead and those release required a manual deployment/were not available for every commit.

https://jitpack.io/#jmfayard/refreshVersions could be a solution to do continuous deployment, but it currently doesn't work, details in the comments.

Other ideas:

- publish plugins like `de.fayard.refreshVersions.dev` with versions like `2021-05-10-1323.$gitSha`
- publish a `1.0-SNAPSHOT` version on mavenCentral

I created an issue for gradle plugin portal https://github.com/gradle/plugin-portal-requests/issues/98

**EDIT:** We will also need to update the releasing script.

**Comment by jmfayard** [comment]
In http4k, I tried to configure jitpack like this:

```kotlin
pluginManagement {
    val version = "0.10.0" 
    val jitpack = "com.github.jmfayard:refreshVersions:6d6eef3"
    repositories {
        gradlePluginPortal()
        if (jitpack.isNotBlank()) maven("https://jitpack.io")
    }
    resolutionStrategy {
        fun module(module: String) = when {
            jitpack.isNotBlank() -> jitpack
            else -> "de.fayard.refreshVersions:$module:$version"
        }
        eachPlugin {
            when (requested.id.id) {
                "de.fayard.refreshVersions" -> useModule(module("refreshVersions"))
                "de.fayard.buildSrcLibs" -> useModule(module("buildSrcLibs"))
            }
        }
    }
}

plugins {
    id("de.fayard.buildSrcLibs") 
    id("de.fayard.refreshVersions") 
}
```

but it fails hard

```
$ ./gradlew help
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all artifacts for configuration 'classpath'.
> Could not find de.fayard.refreshVersions:buildSrcLibs:0.10.0-LOCAL-SNAPSHOT.
  Searched in the following locations:
    - https://plugins.gradle.org/m2/de/fayard/refreshVersions/buildSrcLibs/0.10.0-LOCAL-SNAPSHOT/maven-metadata.xml
    - https://plugins.gradle.org/m2/de/fayard/refreshVersions/buildSrcLibs/0.10.0-LOCAL-SNAPSHOT/buildSrcLibs-0.10.0-LOCAL-SNAPSHOT.pom
    - https://jitpack.io/de/fayard/refreshVersions/buildSrcLibs/0.10.0-LOCAL-SNAPSHOT/maven-metadata.xml
    - https://jitpack.io/de/fayard/refreshVersions/buildSrcLibs/0.10.0-LOCAL-SNAPSHOT/buildSrcLibs-0.10.0-LOCAL-SNAPSHOT.pom
  Required by:
      unspecified:unspecified:unspecified > com.github.jmfayard:refreshVersions:6d6eef3
```

**Comment by jmfayard** [comment]
I just had an idea how to implement continuous deployment

We could simply create new plugins inside **gradlePluginPortal()**

```
plugins {
    id("de.fayard.refreshVersions.dev")
    id("de.fayard.refreshVersions-core.dev")    
    id("de.fayard.buildSrcVersions.dev")
    id("de.fayard.dependencies.dev")    
}
```

For the version number, we can use the **GITHUB_RUN_ID** environment variable

https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables

**Comment by Fleshgrinder** [comment]
Relying on something like `GITHUB_RUN_ID` is always a bad idea because it couples you to the CI/CD system. What you want is usually done via `-SNAPSHOT` in the Java world. You basically bump the version after you made a release and tack `-SNAPSHOT` to the end. Afaik the Gradle plugin portal still has no support for snapshots but Maven Central definitely does and you could publish your snapshots there without making them available on the plugin portal. I actually think that this is best for users because this way they will not see some snapshot version listed as the latest in the plugin portal.

**Comment by vlsi** [comment]
In my experience, "sane changelog" is the most difficult issue to tackle :)

It is really hard to write every commit message in such a way so it is readable "as is" by the end-users.

----

You could publish `-SNAPSHOT` version, and publish it to Maven Central. It would have several great properties:
1) Everybody understands what `-SNAPSHOT` release means
2) The testing for the new version is as easy as adding `-SNAPSHOT` to the version. There's no need to declare custom repositories.
3) You don't pollute Central repository with "rarely used release artifacts". In other words, Central (and all the copies) understand what SNAPSHOT means, and they can delete stale snapshots (which are not really important much).
4) You don't need to generate release notes for every snapshot release

An alternative approach is to cut releases from **every** commit.
For instance, if you use something like `1.2.3.2021-05-10-1323.$gitSha` for the version, then you could have consistent version names.
The drawbacks are:
1) It is harder to plug "the complicated" version, since users won't able to "remember it". It might be solved if you automatically bump version numbers after each release. however, frankly speaking, I hate release processes that require doing commits for the sole purpose of making a release. In my opinion, it should be possible to cut a release from ANY repository state, and even "commit to change from snapshot to non-snapshot" is a no-go.
2) You would pollute the repositories with stale artifacts. Even though space is "free" in Central, I do not think it is fair use of the public resources, and I do not think the added value outweighs the costs. It sounds like waste out of thin air 🤷‍♂️ 
Central won't understand which artifacts are "stale", and it won't be able to delete stale ones.
3) You would have to generate and update release notes on every release. 

I know Mokito is using Shipkit for continuous delivery (see https://github.com/mockito/mockito#development ), however, they do not publish every release to Central. By the way, last time I checked Skipkit, it used dubious Gradle practices so I had to replace Shipkit with another "publish to central" plugin.
