### ISSUE TITLE
How to add agp 7.x as dependency?

### ISSUE THREAD

**Issue by Piasy** [jmfayard/refreshVersions#650]
When creating Android project with latest Android Studio 2021/2022, the root project `build.gradle.kts` file has `plugins` block like:

```kotlin

plugins {
    //trick: for the same plugin versions in all sub-modules
    id("com.android.library").version("7.3.0").apply(false)
    id("com.android.application").version("7.3.0").apply(false)
}
```

How could I declare it with refreshVersions?

**Comment by OKatrych** [comment]
There are two ways:
### A)
Inside `build.gradle.kts`:
```
plugins {
    //trick: for the same plugin versions in all sub-modules
    id("com.android.library").version("_").apply(false)
    id("com.android.application").version("_").apply(false)
}
```
Inside `versions.properties`:
```
plugin.android=7.3.0
```

### B)
Inside project level `build.gradle.kts`:
```
plugins {}
```
Inside `versions.properties`:
```
plugin.android=7.3.0
```
Inside app level `build.gradle.kts`:
```
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}
```

I prefer the second way because refreshVersions automatically adds the version for the plugins.

**Comment by Piasy** [comment]
Thanks!

**Comment by LouisCAD** [comment]
@OKatrych version placeholders (underscores) are not supported in the plugin DSL FYI.
